In [1]:
import numpy as np

In [2]:
arr = np.array(0)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr = np.array([1,2,3,4])

In [7]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
arr = np.array([
    [
        [1,2,3,4],
        [4,5,6,7]
    ],
    [
        [2,3,4,1],
        [2,4,1,1]
    ]
])

print(arr)
type(arr)
print(arr.ndim)
print(arr.astype("float"))

[[[1 2 3 4]
  [4 5 6 7]]

 [[2 3 4 1]
  [2 4 1 1]]]
3
[[[1. 2. 3. 4.]
  [4. 5. 6. 7.]]

 [[2. 3. 4. 1.]
  [2. 4. 1. 1.]]]


In [21]:
arr = np.array([1,2,4,5])
new = arr.copy()
print(new)

new[0] = 9
print(new)
print(arr)

[1 2 4 5]
[9 2 4 5]
[1 2 4 5]


In [26]:
arr = np.array([3,4,5,6])
new = arr.view()
new [0] = 44
print(new)
print(arr)
print(arr.shape)


[44  4  5  6]
[44  4  5  6]
(4,)


In [34]:
arr = np.array([1,2,3,4,5,6,7,8])
new = arr.reshape(2,1,4)
print(new)

[[[1 2 3 4]]

 [[5 6 7 8]]]


In [ ]:
arr = np.array([
    [
        [1,2,3,4],
        [4,5,6,7]
    ],
    [
        [2,3,4,1],
        [2,4,1,1]
    ]
])

print(arr)
type(arr)
print(arr.ndim)
print(arr.astype("float"))


for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [4 5 6 7]]

 [[2 3 4 1]
  [2 4 1 1]]]
3
[[[1. 2. 3. 4.]
  [4. 5. 6. 7.]]

 [[2. 3. 4. 1.]
  [2. 4. 1. 1.]]]
1
2
3
4
4
5
6
7
2
3
4
1
2
4
1
1


In [39]:
arr = np.array([1,2,3,4,5])
np.where(arr ==3)

(array([2]),)